-- ============================================================
-- NEXTRON 2026
-- Participation certificate issuance foundation
--
-- One symposium-wide participation certificate per person.
-- Identity is deduplicated by normalized email because one person
-- may have multiple member rows across different event registrations.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.participant_certificates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Representative member row used when the certificate is issued.
  member_id UUID NOT NULL
    REFERENCES public.members(id)
    ON DELETE RESTRICT,

  certificate_serial BIGINT
    GENERATED BY DEFAULT AS IDENTITY,

  certificate_number TEXT NOT NULL UNIQUE,

  verification_token UUID NOT NULL
    DEFAULT gen_random_uuid()
    UNIQUE,

  -- Snapshot the printed recipient data.
  recipient_name TEXT NOT NULL,
  institution_name TEXT NOT NULL,
  recipient_email TEXT NOT NULL,
  recipient_email_normalized TEXT NOT NULL,

  status TEXT NOT NULL DEFAULT 'ISSUED'
    CHECK (status IN ('ISSUED', 'VOID')),

  issued_by UUID
    REFERENCES public.coordinators(id)
    ON DELETE SET NULL,

  issued_by_name TEXT NOT NULL,

  issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  pdf_path TEXT,
  generated_at TIMESTAMPTZ,

  sent_at TIMESTAMPTZ,
  delivery_status TEXT
    CHECK (
      delivery_status IS NULL
      OR delivery_status IN ('PENDING', 'SENT', 'FAILED')
    ),

  void_reason TEXT,
  voided_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_participant_certificates_status
  ON public.participant_certificates(status);

CREATE INDEX IF NOT EXISTS idx_participant_certificates_member
  ON public.participant_certificates(member_id);

-- Only one active participation certificate per symposium identity.
-- A VOID historical record does not prevent a corrected re-issue.
CREATE UNIQUE INDEX IF NOT EXISTS
  uq_participant_certificates_issued_email
ON public.participant_certificates(recipient_email_normalized)
WHERE status = 'ISSUED';

ALTER TABLE public.participant_certificates
  ENABLE ROW LEVEL SECURITY;

REVOKE ALL
ON TABLE public.participant_certificates
FROM anon, authenticated;


-- ============================================================
-- ADMIN: LIST ELIGIBLE PARTICIPANTS
--
-- Eligibility:
--   - same identity has at least one PRESENT attendance
--   - same identity has NO prize-winner row
--   - same identity has no certificate already issued
--
-- Normalized email is used as the symposium-wide identity key.
-- ============================================================

CREATE OR REPLACE FUNCTION public.get_participation_certificate_candidates(
  p_token TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_session RECORD;
  v_user RECORD;
  v_result JSONB;
BEGIN
  SELECT *
  INTO v_session
  FROM public.app_sessions
  WHERE token = p_token
    AND expires_at > now()
  LIMIT 1;

  IF v_session IS NULL THEN
    RAISE EXCEPTION 'Unauthorized: Invalid or expired session';
  END IF;

  SELECT *
  INTO v_user
  FROM public.coordinators
  WHERE id = v_session.user_id
    AND is_active = true
  LIMIT 1;

  IF v_user IS NULL OR v_user.role <> 'admin' THEN
    RAISE EXCEPTION 'Unauthorized: Admin access required';
  END IF;

  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'member_id', q.member_id,
        'name', q.full_name,
        'email', q.email,
        'college', q.college_name,
        'registration_number', q.registration_number,
        'event', q.event_name,
        'attendance_marked_at', q.attendance_marked_at
      )
      ORDER BY q.full_name ASC
    ),
    '[]'::jsonb
  )
  INTO v_result
  FROM (
    SELECT DISTINCT ON (lower(trim(m.email)))
      m.id AS member_id,
      m.full_name,
      m.email,
      r.college_name,
      r.registration_number,
      e.name AS event_name,
      ma.marked_at AS attendance_marked_at

    FROM public.members m

    JOIN public.registrations r
      ON r.id = m.registration_id

    JOIN public.events e
      ON e.id = r.event_id

    JOIN public.member_attendance ma
      ON ma.member_id = m.id
     AND ma.status = 'PRESENT'

    WHERE
      NULLIF(lower(trim(m.email)), '') IS NOT NULL

      -- If this identity won in ANY event, no online participation certificate.
      AND NOT EXISTS (
        SELECT 1
        FROM public.members wm
        JOIN public.member_prize_winners mpw
          ON mpw.member_id = wm.id
        WHERE lower(trim(wm.email)) = lower(trim(m.email))
      )

      -- Already issued identities should not appear again.
      AND NOT EXISTS (
        SELECT 1
        FROM public.participant_certificates pc
        WHERE pc.recipient_email_normalized =
              lower(trim(m.email))
          AND pc.status = 'ISSUED'
      )

    ORDER BY
      lower(trim(m.email)),
      ma.marked_at ASC,
      m.id ASC
  ) q;

  RETURN v_result;
END;
$$;

REVOKE ALL
ON FUNCTION public.get_participation_certificate_candidates(TEXT)
FROM PUBLIC;

GRANT EXECUTE
ON FUNCTION public.get_participation_certificate_candidates(TEXT)
TO anon, authenticated;


-- ============================================================
-- ADMIN: ISSUE ONE PARTICIPATION CERTIFICATE
--
-- Idempotent:
-- if this identity already has an ISSUED certificate, return it.
-- ============================================================

CREATE OR REPLACE FUNCTION public.issue_participation_certificate(
  p_token TEXT,
  p_member_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_session RECORD;
  v_user RECORD;
  v_member RECORD;
  v_email_norm TEXT;
  v_existing RECORD;
  v_serial BIGINT;
  v_number TEXT;
  v_certificate RECORD;
BEGIN
  SELECT *
  INTO v_session
  FROM public.app_sessions
  WHERE token = p_token
    AND expires_at > now()
  LIMIT 1;

  IF v_session IS NULL THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'Unauthorized: Invalid or expired session'
    );
  END IF;

  SELECT *
  INTO v_user
  FROM public.coordinators
  WHERE id = v_session.user_id
    AND is_active = true
  LIMIT 1;

  IF v_user IS NULL OR v_user.role <> 'admin' THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'Unauthorized: Admin access required'
    );
  END IF;

  SELECT
    m.id,
    m.full_name,
    m.email,
    r.college_name,
    r.registration_number
  INTO v_member
  FROM public.members m
  JOIN public.registrations r
    ON r.id = m.registration_id
  WHERE m.id = p_member_id
  LIMIT 1;

  IF v_member IS NULL THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'Member not found'
    );
  END IF;

  v_email_norm := lower(trim(v_member.email));

  IF v_email_norm IS NULL OR v_email_norm = '' THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'Member email is required for certificate issuance'
    );
  END IF;

  -- Serialize concurrent issuance attempts for the same identity.
  -- This keeps double-clicks / parallel requests idempotent.
  PERFORM pg_advisory_xact_lock(
    hashtext(v_email_norm)::bigint
  );

  -- Existing certificate: idempotently return it.
  SELECT *
  INTO v_existing
  FROM public.participant_certificates
  WHERE recipient_email_normalized = v_email_norm
    AND status = 'ISSUED'
  LIMIT 1;

  IF v_existing IS NOT NULL THEN
    RETURN jsonb_build_object(
      'success', true,
      'already_issued', true,
      'certificate_id', v_existing.id,
      'certificate_number', v_existing.certificate_number,
      'verification_token', v_existing.verification_token
    );
  END IF;

  -- The exact member record selected for issuance must be PRESENT.
  -- This guarantees the printed name / institution come from an
  -- actually attended registration.
  IF NOT EXISTS (
    SELECT 1
    FROM public.member_attendance ma
    WHERE ma.member_id = v_member.id
      AND ma.status = 'PRESENT'
  ) THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'Participant is not marked PRESENT'
    );
  END IF;

  -- Identity must not be a prize winner in any event.
  IF EXISTS (
    SELECT 1
    FROM public.members wm
    JOIN public.member_prize_winners mpw
      ON mpw.member_id = wm.id
    WHERE lower(trim(wm.email)) = v_email_norm
  ) THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'Prize winners receive their certificate offline'
    );
  END IF;

  -- Insert first so the database identity value allocates a serial.
  INSERT INTO public.participant_certificates (
    member_id,
    certificate_number,
    recipient_name,
    institution_name,
    recipient_email,
    recipient_email_normalized,
    issued_by,
    issued_by_name
  )
  VALUES (
    v_member.id,
    'PENDING-' || gen_random_uuid()::text,
    v_member.full_name,
    v_member.college_name,
    v_member.email,
    v_email_norm,
    v_user.id,
    v_user.name
  )
  RETURNING *
  INTO v_certificate;

  v_serial := v_certificate.certificate_serial;

  v_number :=
    'NXT26-P-' ||
    lpad(v_serial::text, 6, '0');

  UPDATE public.participant_certificates
  SET
    certificate_number = v_number,
    updated_at = now()
  WHERE id = v_certificate.id
  RETURNING *
  INTO v_certificate;

  RETURN jsonb_build_object(
    'success', true,
    'already_issued', false,
    'certificate_id', v_certificate.id,
    'certificate_number', v_certificate.certificate_number,
    'verification_token', v_certificate.verification_token,
    'recipient_name', v_certificate.recipient_name,
    'institution_name', v_certificate.institution_name,
    'recipient_email', v_certificate.recipient_email,
    'issued_at', v_certificate.issued_at
  );
END;
$$;

REVOKE ALL
ON FUNCTION public.issue_participation_certificate(TEXT, UUID)
FROM PUBLIC;

GRANT EXECUTE
ON FUNCTION public.issue_participation_certificate(TEXT, UUID)
TO anon, authenticated;
